-- 6. Create Leads Table
CREATE TABLE public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR NOT NULL,
  mobile VARCHAR NOT NULL,
  property_address TEXT NOT NULL,
  service_required VARCHAR NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'New Lead',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Payments Table (if distinct from rent_payments)
CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id BIGINT REFERENCES public.agreements(id),
  amount DECIMAL NOT NULL,
  payment_date DATE,
  status VARCHAR NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Biometric Visits Table
CREATE TABLE public.biometric_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id BIGINT REFERENCES public.agreements(id) NOT NULL,
  vendor_name VARCHAR NOT NULL,
  visit_date DATE NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'Assigned',
  remarks TEXT,
  photo_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Create Renewal Leads Table
CREATE TABLE public.renewal_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id BIGINT REFERENCES public.agreements(id) NOT NULL,
  expiry_date DATE NOT NULL,
  days_until_expiry INT NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'New',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: Ensure real-time is enabled on these tables for the admin dashboard!
ALTER TABLE public.leads REPLICA IDENTITY FULL;
ALTER TABLE public.payments REPLICA IDENTITY FULL;
ALTER TABLE public.biometric_visits REPLICA IDENTITY FULL;
ALTER TABLE public.renewal_leads REPLICA IDENTITY FULL;
