-- Create agreement_timeline table to track status changes

CREATE TABLE public.agreement_timeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id BIGINT REFERENCES public.agreements(id) ON DELETE CASCADE NOT NULL,
  status_step VARCHAR NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.agreement_timeline ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read and insert into agreement_timeline
CREATE POLICY "Allow authenticated read on agreement_timeline"
ON public.agreement_timeline
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert on agreement_timeline"
ON public.agreement_timeline
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Note: The admin will insert a row here every time the agreement status changes.

-- ALSO: Remove any old restrictions on the agreement status column so we can use our new timeline statuses
ALTER TABLE public.agreements DROP CONSTRAINT IF EXISTS agreements_status_check;
