-- Vakil Sirji Property Manager - Supabase SQL Setup

-- 1. Create Users Table
-- Note: Supabase already has an 'auth.users' table for login credentials.
-- We create a public.users table to store extended profile information.
CREATE TABLE public.users (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  name VARCHAR NOT NULL,
  mobile VARCHAR,
  email VARCHAR UNIQUE NOT NULL,
  role VARCHAR NOT NULL CHECK (role IN ('owner', 'tenant', 'admin', 'vendor')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Properties Table
CREATE TABLE public.properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES public.users(id) NOT NULL,
  property_name VARCHAR NOT NULL,
  address TEXT NOT NULL,
  city VARCHAR NOT NULL,
  rent_amount DECIMAL NOT NULL,
  deposit DECIMAL NOT NULL,
  status VARCHAR NOT NULL CHECK (status IN ('active', 'vacant')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Tenants Table (Linking tenants to properties)
CREATE TABLE public.tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) NOT NULL,
  user_id UUID REFERENCES public.users(id) NOT NULL,
  aadhaar_last4 VARCHAR(4) NOT NULL,
  start_date DATE NOT NULL,r
  end_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Agreements Table
CREATE TABLE public.agreements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) NOT NULL,
  tenant_id BIGINT REFERENCES public.tenants(id) NOT NULL,
  agreement_number VARCHAR NOT NULL UNIQUE,
  start_date DATE NOT NULL,
  expiry_date DATE NOT NULL,
  pdf_url TEXT,
  status VARCHAR NOT NULL CHECK (status IN ('active', 'expired')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Rent Payments Table
CREATE TABLE public.rent_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) NOT NULL,
  tenant_id BIGINT REFERENCES public.tenants(id) NOT NULL,
  amount DECIMAL NOT NULL,
  payment_date DATE,
  month VARCHAR NOT NULL,
  status VARCHAR NOT NULL CHECK (status IN ('paid', 'pending')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Row Level Security (RLS) Setup (Basic setup allowing everything for MVP testing)
-- IN PRODUCTION, you should restrict these policies based on roles.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rent_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for authenticated users" ON public.users FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all operations for authenticated users" ON public.properties FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all operations for authenticated users" ON public.tenants FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all operations for authenticated users" ON public.agreements FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all operations for authenticated users" ON public.rent_payments FOR ALL USING (auth.role() = 'authenticated');

