-- 1. Create Leads Table
CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name VARCHAR NOT NULL,
  phone VARCHAR NOT NULL,
  property_address TEXT NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Documents Collected', 'Drafted', 'Filed', 'Registered')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Lead Documents Table
CREATE TABLE IF NOT EXISTS public.lead_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES public.leads(id) ON DELETE CASCADE NOT NULL,
  document_type VARCHAR NOT NULL, -- e.g. 'Electricity Bill', 'Owner Aadhaar'
  file_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. RLS
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for authenticated users" ON public.leads FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all operations for authenticated users" ON public.lead_documents FOR ALL USING (auth.role() = 'authenticated');

-- 4. Enable Supabase Storage (Run these commands or create bucket manually in Dashboard)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('lead_documents', 'lead_documents', true);
-- CREATE POLICY "Public Access" ON storage.objects FOR ALL USING (bucket_id = 'lead_documents');
