[build]
  command = "rm -rf _flutter && git clone https://github.com/flutter/flutter.git -b stable --depth 1 _flutter && echo \"SUPABASE_URL=$SUPABASE_URL\" > .env && echo \"SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY\" >> .env && _flutter/bin/flutter build web --release --no-wasm-dry-run && rm -f .env"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""
